version: '2.4'
services:

  build_linux:
    image: docker.digimarc.net/comm/es/linux/ubuntu1804_base:1.1
    stdin_open: true
    tty: true
    volumes:
      - ./:/work
    working_dir: /work
    entrypoint: /bin/bash
    command: ./test.bash

  build_linux_multiarch:
    extends: build_linux
    image: docker.digimarc.net/comm/es/linux/ubuntu1804_multiarch:1.1.0

  build_linux_clang:
    extends: build_linux
    image: docker.digimarc.net/comm/es/linux/ubuntu1804_clang:1.1.1

  build_linux_arm:
    extends: build_linux
    image: docker.digimarc.net/comm/es/linux/ubuntu1804_arm:1.1.0